#############################################################################
# Makefile for building: tlk
# Generated by qmake (2.01a) (Qt 4.8.0) on: Sun Mar 18 18:06:52 2012
# Project:  tlk.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile tlk.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = aboutdialog.cpp \
		main.cpp \
		pal.cpp \
		palwindow.cpp \
		rec_thread.cpp \
		toc_window.cpp moc_aboutdialog.cpp \
		moc_pal.cpp \
		moc_palwindow.cpp \
		moc_rec_thread.cpp \
		moc_toc_window.cpp
OBJECTS       = aboutdialog.o \
		main.o \
		pal.o \
		palwindow.o \
		rec_thread.o \
		toc_window.o \
		moc_aboutdialog.o \
		moc_pal.o \
		moc_palwindow.o \
		moc_rec_thread.o \
		moc_toc_window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		tlk.pro
QMAKE_TARGET  = tlk
DESTDIR       = 
TARGET        = tlk

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tlk.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile tlk.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile tlk.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tlk1.0.0 || $(MKDIR) .tmp/tlk1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tlk1.0.0/ && $(COPY_FILE) --parents aboutdialog.h pal.h palwindow.h rec_thread.h toc_window.h .tmp/tlk1.0.0/ && $(COPY_FILE) --parents aboutdialog.cpp main.cpp pal.cpp palwindow.cpp rec_thread.cpp toc_window.cpp .tmp/tlk1.0.0/ && (cd `dirname .tmp/tlk1.0.0` && $(TAR) tlk1.0.0.tar tlk1.0.0 && $(COMPRESS) tlk1.0.0.tar) && $(MOVE) `dirname .tmp/tlk1.0.0`/tlk1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tlk1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_aboutdialog.cpp moc_pal.cpp moc_palwindow.cpp moc_rec_thread.cpp moc_toc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_aboutdialog.cpp moc_pal.cpp moc_palwindow.cpp moc_rec_thread.cpp moc_toc_window.cpp
moc_aboutdialog.cpp: aboutdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) aboutdialog.h -o moc_aboutdialog.cpp

moc_pal.cpp: pal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) pal.h -o moc_pal.cpp

moc_palwindow.cpp: palwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) palwindow.h -o moc_palwindow.cpp

moc_rec_thread.cpp: rec_thread.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) rec_thread.h -o moc_rec_thread.cpp

moc_toc_window.cpp: rec_thread.h \
		pal.h \
		aboutdialog.h \
		toc_window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) toc_window.h -o moc_toc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

aboutdialog.o: aboutdialog.cpp aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o aboutdialog.o aboutdialog.cpp

main.o: main.cpp toc_window.h \
		rec_thread.h \
		pal.h \
		aboutdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pal.o: pal.cpp pal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pal.o pal.cpp

palwindow.o: palwindow.cpp palwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o palwindow.o palwindow.cpp

rec_thread.o: rec_thread.cpp rec_thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rec_thread.o rec_thread.cpp

toc_window.o: toc_window.cpp toc_window.h \
		rec_thread.h \
		pal.h \
		aboutdialog.h \
		palwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toc_window.o toc_window.cpp

moc_aboutdialog.o: moc_aboutdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_aboutdialog.o moc_aboutdialog.cpp

moc_pal.o: moc_pal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pal.o moc_pal.cpp

moc_palwindow.o: moc_palwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_palwindow.o moc_palwindow.cpp

moc_rec_thread.o: moc_rec_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rec_thread.o moc_rec_thread.cpp

moc_toc_window.o: moc_toc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_toc_window.o moc_toc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

